### ISSUE TITLE
Need a Logo For the Project 

### ISSUE THREAD

**Issue by vaaibhavsharma** [vaaibhavsharma/rehash#2]
Simple Minimalist LOGO

**Comment by Naman-X15** [comment]
hey @vaaibhavsharma I have made a simple logo

**Comment by Ashpreetwadhwa** [comment]
hey @vaaibhavsharma you can assign me this task

**Comment by Ashpreetwadhwa** [comment]
![WhatsApp Image 2022-10-10 at 18 56 18 (1)](https://user-images.githubusercontent.com/102176527/194877262-f2320547-696a-49eb-be6a-fbd6d31d91c3.jpeg)
![WhatsApp Image 2022-10-10 at 18 56 18](https://user-images.githubusercontent.com/102176527/194877270-ebb4207b-7c72-4a63-865f-a7e80c123a83.jpeg)
![WhatsApp Image 2022-10-10 at 18 56 17](https://user-images.githubusercontent.com/102176527/194877273-c133b654-de08-40f2-9b41-09939a617f65.jpeg)
Hey @vaaibhavsharma please brief me about which type of logo do you want
A name logo or elemental.

**Comment by vaaibhavsharma** [comment]
name logo

**Comment by Ashpreetwadhwa** [comment]
Did you like any one of the above logo

**Comment by Ashpreetwadhwa** [comment]
Please can you describe which type of logo you want
